main: install

install: 
	rm package-lock.json
	npm install --save @metaplex/js
	npm install --save @project-serum/anchor
	npm install --save @solana/wallet-adapter-base
	npm install --save @testing-library/jest-dom
	npm install --save @testing-library/user-event
	npm install --save react
	npm install --save react-dom
	npm install --save react-scripts
	npm install --save web-vitals
	
run:
	npm start run

build:
	npm build