[features]
seeds = false
skip-lint = false
[programs.localnet]
crowdfunding = "7EpjcPETt3UfaDcze1YDhr7WRPxqUdvC4MhXSeoHmZDU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
